---

env: prod
server:
  port: :8080
  read_timeout: 5
  write_timeout: 4
  idle_timeout: 100
db:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbname: cryptoInfo
  sslmode: disable
  timezone: Europe/Minsk

