version: '3'

services:
  postgres:
    image: postgres:alpine
    container_name: ps
    restart: unless-stopped
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}  
      - TZ=${TZ}
    ports:
      - "5433:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: rd
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - rd_db:/data

  api:
    build: .
    hostname: api
    container_name: api
    env_file:
        - .env
    ports:
      - "8080:8080"
    depends_on:
        - postgres
        - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    ports:
      - "5044:5044"  
      - "9600:9600" 
    volumes:
      - ./elk/configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf  
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"  
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: filebeat
    user: root
    volumes:
      - ./elk/configs/filebeat.yaml:/usr/share/filebeat/filebeat.yml
      - ./logs:/logs 
    command: ["filebeat", "-e"]
    depends_on:
      - logstash


volumes:
  pg_db:
    driver: local
  rd_db:
    driver: local
  esdata:
    driver: local

