version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crypto_info  
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    hostname: api
    container_name: api
    env_file:
        - .env
    ports:
      - "8080:8080"
    depends_on:
        - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    ports:
      - "5044:5044"  
      - "9600:9600" 
    volumes:
      - ./elk/configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf  
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"  
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: filebeat
    user: root
    volumes:
      - ./elk/configs/filebeat.yaml:/usr/share/filebeat/filebeat.yml
      - ./logs:/logs 
    command: ["filebeat", "-e"]
    depends_on:
      - logstash


volumes:
  pgdata:
    driver: local
  esdata:
    driver: local

